### ISSUE TITLE
No application is shown on the app list even after installing all the dependencies successfully

### ISSUE THREAD

**Issue by utpalgohain** [S3Jensen/iRET#7]
Device used : iPhone 6 + 
OS jail break version 8.1.3 installation with TaiG.

Let me know if there is any thing is missed out during installation.Please see the application screen attached.

Tx

utpal
![no application list shown](https://cloud.githubusercontent.com/assets/3095373/9563884/11b60a74-4eb1-11e5-8a69-089ebd6944d0.png)

**Comment by S3Jensen** [comment]
I am in the process of updating iRET for iOS 8/9. I should have an update release available in the coming weeks.

**Comment by utpalgohain** [comment]
Could you please update us when you are releasing the patch. Also the date or any kind of update would be great.

Thanks 
utpal
